"""initial schema

Revision ID: 8b53d6569dbd
Revises: 
Create Date: 2026-09-03 08:58:29.361707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b53d6569dbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_activity',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_activity_at'), 'agent_activity', ['at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('finding_id', sa.String(), nullable=True),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('audit_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('actor_kind', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_at'), 'audit_entries', ['at'], unique=False)
    op.create_table('fixes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('hunks', sa.JSON(), nullable=False),
    sa.Column('prevents', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pull_request', sa.JSON(), nullable=True),
    sa.Column('revert_reason', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixes_investigation_id'), 'fixes', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_fixes_status'), 'fixes', ['status'], unique=False)
    op.create_table('historical_incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('root_cause', sa.JSON(), nullable=False),
    sa.Column('recovery_hours', sa.Float(), nullable=False),
    sa.Column('pattern_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('pipeline', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('commit', sa.String(), nullable=False),
    sa.Column('commit_message', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('fix_id', sa.String(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('hypotheses', sa.JSON(), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=False),
    sa.Column('similar_changes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_decision'), 'investigations', ['decision'], unique=False)
    op.create_index(op.f('ix_investigations_finding_id'), 'investigations', ['finding_id'], unique=False)
    op.create_index(op.f('ix_investigations_severity'), 'investigations', ['severity'], unique=False)
    op.create_table('learned_patterns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('statement', sa.JSON(), nullable=False),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_matched', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('cited_by', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('statement', sa.JSON(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('enforcement', sa.String(), nullable=False),
    sa.Column('violations', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recorded_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('investigation_ids', sa.JSON(), nullable=False),
    sa.Column('response_count', sa.Integer(), nullable=False),
    sa.Column('gateway_version', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fix_id', sa.String(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.JSON(), nullable=False),
    sa.Column('required_approvals', sa.Integer(), nullable=False),
    sa.Column('approvals', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sla_hours_remaining', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_fix_id'), 'review_items', ['fix_id'], unique=False)
    op.create_index(op.f('ix_review_items_investigation_id'), 'review_items', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_review_items_severity'), 'review_items', ['severity'], unique=False)
    op.create_index(op.f('ix_review_items_status'), 'review_items', ['status'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviews_completed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('findings_opened', sa.Integer(), nullable=False),
    sa.Column('findings_resolved', sa.Integer(), nullable=False),
    sa.Column('auto_fixed', sa.Integer(), nullable=False),
    sa.Column('flagged', sa.Integer(), nullable=False),
    sa.Column('refused', sa.Integer(), nullable=False),
    sa.Column('mttr_hours', sa.Float(), nullable=False),
    sa.Column('annotation', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_points_date'), 'trend_points', ['date'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('delivery_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id', name='uq_webhook_delivery_id')
    )
    op.create_index(op.f('ix_webhook_events_delivery_id'), 'webhook_events', ['delivery_id'], unique=True)
    op.create_table('repositories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monitored', sa.Boolean(), nullable=False),
    sa.Column('installation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_full_name'), 'repositories', ['full_name'], unique=True)
    op.create_index(op.f('ix_repositories_organization_id'), 'repositories', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviews_completed', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('touches_production', sa.Boolean(), nullable=False),
    sa.Column('environments', sa.JSON(), nullable=False),
    sa.Column('secrets_used', sa.JSON(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_repository_id'), 'pipelines', ['repository_id'], unique=False)
    op.create_table('dependency_graphs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_graphs_pipeline_id'), 'dependency_graphs', ['pipeline_id'], unique=True)
    op.create_table('findings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repository_id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('title', sa.JSON(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('line', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('impact', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('cwe', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_pipeline_id'), 'findings', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_findings_repository_id'), 'findings', ['repository_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('needs', sa.JSON(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('secrets', sa.JSON(), nullable=False),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('avg_duration_ms', sa.Integer(), nullable=False),
    sa.Column('finding_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_jobs_pipeline_id'), 'pipeline_jobs', ['pipeline_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('commit', sa.String(), nullable=False),
    sa.Column('commit_message', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('finding_ids', sa.JSON(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('workflow_run_id', sa.String(), nullable=True),
    sa.Column('github_delivery_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_github_delivery_id'), 'pipeline_runs', ['github_delivery_id'], unique=True)
    op.create_index(op.f('ix_pipeline_runs_pipeline_id'), 'pipeline_runs', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_workflow_run_id'), 'pipeline_runs', ['workflow_run_id'], unique=False)
    op.create_table('run_trace_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_trace_events_run_id'), 'run_trace_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_trace_events_stage'), 'run_trace_events', ['stage'], unique=False)
    op.create_index('ix_trace_run_stage', 'run_trace_events', ['run_id', 'stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trace_run_stage', table_name='run_trace_events')
    op.drop_index(op.f('ix_run_trace_events_stage'), table_name='run_trace_events')
    op.drop_index(op.f('ix_run_trace_events_run_id'), table_name='run_trace_events')
    op.drop_table('run_trace_events')
    op.drop_index(op.f('ix_pipeline_runs_workflow_run_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_pipeline_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_github_delivery_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_pipeline_jobs_pipeline_id'), table_name='pipeline_jobs')
    op.drop_table('pipeline_jobs')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_repository_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_pipeline_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_dependency_graphs_pipeline_id'), table_name='dependency_graphs')
    op.drop_table('dependency_graphs')
    op.drop_index(op.f('ix_pipelines_repository_id'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_repositories_organization_id'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_full_name'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_webhook_events_delivery_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_trend_points_date'), table_name='trend_points')
    op.drop_table('trend_points')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_review_items_status'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_severity'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_investigation_id'), table_name='review_items')
    op.drop_index(op.f('ix_review_items_fix_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_table('recorded_runs')
    op.drop_table('policies')
    op.drop_table('organizations')
    op.drop_table('learned_patterns')
    op.drop_index(op.f('ix_investigations_severity'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_finding_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_decision'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_table('integrations')
    op.drop_table('historical_incidents')
    op.drop_index(op.f('ix_fixes_status'), table_name='fixes')
    op.drop_index(op.f('ix_fixes_investigation_id'), table_name='fixes')
    op.drop_table('fixes')
    op.drop_index(op.f('ix_audit_entries_at'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_agent_activity_at'), table_name='agent_activity')
    op.drop_table('agent_activity')
    # ### end Alembic commands ###
